services:
  bos-app:
    build:
      context: ./bos-app
    container_name: nodejsserver
    hostname: nodejsserver
    ports:
      - "5000:5000"
    networks:
      - example-net
    depends_on:
      - mongo
  mongo:
      container_name: mongo
      image: mongo
      volumes:
        - ./data:/data/db
      ports:
        - "27017:27017"
      networks:
        - example-net
  nginx:
        build:
          context: ./nginx
        container_name: nginx
        hostname: nginx
        ports:
          - "80:80"
        depends_on:
          - nodejs-app
        networks:
          - example-net