{
       
    "is_task_done" : false,
    "is_task_rollovered" : false,
    "Monday" : false,
    "Thuesday" : false,
    "Wednesday" : false,
    "Thudesday" : false,
    "Friday" : false,
    "Saturday" : false,
    "Sunday" : false,
    "ID" : "4cd82f35-140d-4624-a330-192ec70f4d8b",
    "Short_description" : "Start Up Procedure",
    "Summary" : "This is a series of actions the will help you set up correctly for the day.  Things to do: 1. Have you turned the alarm off 2. Unlock Cool Room B 3. Turn on light to Coolroom B,C & D 4. Unlock Coolroom C 5. Collect personal items that you will need throughout the morning PEN, RADIO,KNIFE & THERMOMETER",
    "Priority" : "High",
    "start_date_time" : "2023-09-11",
    "end_date_time" : "2023-09-11",
    "Task_Recurrence" : "Daily",
    "Assign_to_User" : "Zoe",
    "Assign_to_Department" : "",
    "Escalated_to_User" : "",
    "Escalated_to_Department" : "Picking",
    "Email_Notify" : true,
    "end_time" : "12:00",
    "start_time" : "05:00",
    "Task_Date" : "2023-09-11",
    "__v" : 0
},
{
   
    "is_task_done" : false,
    "is_task_rollovered" : false,
    "Monday" : false,
    "Thuesday" : false,
    "Wednesday" : false,
    "Thudesday" : false,
    "Friday" : false,
    "Saturday" : false,
    "Sunday" : false,
    "ID" : "1e89e19d-77c4-42a0-9b2e-4c8020d39e3d",
    "Short_description" : "Check Answering machine for overnight orders & Invoice",
    "Summary" : "Check Answering machine for overnight orders - ",
    "Priority" : "High",
    "start_date_time" : "2023-09-11",
    "end_date_time" : "2023-09-11",
    "Task_Recurrence" : "Daily",
    "Assign_to_User" : "Zoe",
    "Assign_to_Department" : "",
    "Escalated_to_User" : "",
    "Escalated_to_Department" : "Picking",
    "Email_Notify" : false,
    "end_time" : "04:10",
    "start_time" : "03:10",
    "Task_Date" : "2023-09-11",
    "__v" : 0
},
{
   
    "is_task_done" : false,
    "is_task_rollovered" : false,
    "Monday" : false,
    "Thuesday" : false,
    "Wednesday" : false,
    "Thudesday" : false,
    "Friday" : false,
    "Saturday" : false,
    "Sunday" : false,
    "ID" : "c0903903-100d-4b59-b794-af763a6339f8",
    "Short_description" : "Turn ON Production Room Refrigeration",
    "Summary" : "Turn ON Production Room Refrigeration  Reason we do this is to precool the area ready for prodcution to begin by 5am. Especially critical through NOV - MAR  Things to look out for: 1. All doors on the production floor are closed you MUSt walk around and check. 2. Switch on the remaining displays panels found opposite time clock. 3. The turn of fresh air fans found to the right of the time clock and close covers.",
    "Priority" : "Critical",
    "start_date_time" : "2023-09-11",
    "end_date_time" : "2023-09-11",
    "Task_Recurrence" : "Daily",
    "Assign_to_User" : "",
    "Assign_to_Department" : "",
    "Escalated_to_User" : "",
    "Escalated_to_Department" : "",
    "Email_Notify" : false,
    "end_time" : "04:15",
    "start_time" : "03:15",
    "Task_Date" : "2023-09-11",
    "__v" : 0
},
{

    "is_task_done" : false,
    "is_task_rollovered" : false,
    "Monday" : false,
    "Thuesday" : false,
    "Wednesday" : false,
    "Thudesday" : false,
    "Friday" : false,
    "Saturday" : false,
    "Sunday" : false,
    "ID" : "0d46fb13-c59e-4c70-9e31-781920d1ae61",
    "Short_description" : "Turn ON Production Room Refrigeration",
    "Summary" : "Turn ON Production Room Refrigeration  Reason we do this is to precool the area ready for prodcution to begin by 5am. Especially critical through NOV - MAR  Things to look out for: 1. All doors on the production floor are closed you MUSt walk around and check. 2. Switch on the remaining displays panels found opposite time clock. 3. The turn of fresh air fans found to the right of the time clock and close covers.",
    "Priority" : "High",
    "start_date_time" : "2023-09-11",
    "end_date_time" : "2023-09-11",
    "Task_Recurrence" : "Daily",
    "Assign_to_User" : "Zoe",
    "Assign_to_Department" : "",
    "Escalated_to_User" : "",
    "Escalated_to_Department" : "Picking",
    "Email_Notify" : false,
    "end_time" : "04:15",
    "start_time" : "03:15",
    "Task_Date" : "2023-09-11",
    "__v" : 0
},
{

    "is_task_done" : false,
    "is_task_rollovered" : false,
    "Monday" : false,
    "Thuesday" : false,
    "Wednesday" : false,
    "Thudesday" : false,
    "Friday" : false,
    "Saturday" : false,
    "Sunday" : false,
    "ID" : "535201bd-690e-4337-b379-e116add4c9ad",
    "Short_description" : "Check / Print Invoice ",
    "Summary" : "Check / Print Invoice -  This task is very importatnt because customers can order online which wont be picked up unless you run this report. Finding an invoice in the system as you are loading a truck can make your job very stressful so running this report is very important.",
    "Priority" : "High",
    "start_date_time" : "2023-09-11",
    "end_date_time" : "2023-09-11",
    "Task_Recurrence" : "Daily",
    "Assign_to_User" : "Zoe",
    "Assign_to_Department" : "",
    "Escalated_to_User" : "",
    "Escalated_to_Department" : "Picking",
    "Email_Notify" : false,
    "end_time" : "04:15",
    "start_time" : "03:15",
    "Task_Date" : "2023-09-11",
    "__v" : 0
},
{

    "is_task_done" : false,
    "is_task_rollovered" : false,
    "Monday" : false,
    "Thuesday" : false,
    "Wednesday" : false,
    "Thudesday" : false,
    "Friday" : false,
    "Saturday" : false,
    "Sunday" : false,
    "ID" : "51e2e1e7-c690-4b1b-957e-d41b400a75f2",
    "Short_description" : "Print WV Shorts report & Print labels",
    "Summary" : "Print WV Shorts report & Print labels.  Using the software \"UniFresh Labels normal\" print labels ensuring the dates are packed on the same day as dispatch.   Check production tray for labels that have already been printed.",
    "Priority" : "High",
    "start_date_time" : "2023-09-11",
    "end_date_time" : "2023-09-11",
    "Task_Recurrence" : "Daily",
    "Assign_to_User" : "Zoe",
    "Assign_to_Department" : "",
    "Escalated_to_User" : "",
    "Escalated_to_Department" : "Picking",
    "Email_Notify" : false,
    "end_time" : "04:14",
    "start_time" : "03:14",
    "Task_Date" : "2023-09-11",
    "__v" : 0
},
{
    
    "is_task_done" : false,
    "is_task_rollovered" : false,
    "Monday" : false,
    "Thuesday" : false,
    "Wednesday" : false,
    "Thudesday" : false,
    "Friday" : false,
    "Saturday" : false,
    "Sunday" : false,
    "ID" : "b3742e93-0183-4c44-8f8e-82dc420fd81b",
    "Short_description" : "Print Driver Load report",
    "Summary" : "Print Driver Load report -  This is the report drivers use to check there quantities before loading.  The report is under the distribution tab in Ostendo \" Driver Load Report\" select day nd print.  Note: If nothing shows up, it means that the order hasn't be picked in the picking software.",
    "Priority" : "High",
    "start_date_time" : "2023-09-11",
    "end_date_time" : "2023-09-11",
    "Task_Recurrence" : "Daily",
    "Assign_to_User" : "Zoe",
    "Assign_to_Department" : "",
    "Escalated_to_User" : "",
    "Escalated_to_Department" : "Picking",
    "Email_Notify" : false,
    "end_time" : "04:15",
    "start_time" : "03:15",
    "Task_Date" : "2023-09-11",
    "__v" : 0
},
{

    "is_task_done" : false,
    "is_task_rollovered" : false,
    "Monday" : false,
    "Thuesday" : false,
    "Wednesday" : false,
    "Thudesday" : false,
    "Friday" : false,
    "Saturday" : false,
    "Sunday" : false,
    "ID" : "6c5a1282-e24c-46c9-a686-954f9ecfa492",
    "Short_description" : "Organise Load allocations",
    "Summary" : "Organise Load allocations  There are additional deliveries that can be done by our regular Metro Deliveries.  This is the list: NORTH - Dennis, Broken Hill NORTH EAST/CITY EAST - San Remo, Gallipo. CITY SOUTH, CENTRAL, SOUTH - Vilis",
    "Priority" : "Critical",
    "start_date_time" : "2023-09-11",
    "end_date_time" : "2023-09-11",
    "Task_Recurrence" : "Daily",
    "Assign_to_User" : "Zoe",
    "Assign_to_Department" : "",
    "Escalated_to_User" : "",
    "Escalated_to_Department" : "Picking",
    "Email_Notify" : false,
    "end_time" : "04:15",
    "start_time" : "03:15",
    "Task_Date" : "2023-09-11",
    "__v" : 0
},
{
    "is_task_done" : false,
    "is_task_rollovered" : false,
    "Monday" : false,
    "Thuesday" : false,
    "Wednesday" : false,
    "Thudesday" : false,
    "Friday" : false,
    "Saturday" : false,
    "Sunday" : false,
    "ID" : "a1fdb578-2494-4860-8280-7dafc6e868cd",
    "Short_description" : "Load Early Morning HS Fresh/ Market Truck SB94NP",
    "Summary" : "Load Early Morning SunFresh/ Market Truck SB94NP  Load in this order: 1.Market return 2. Central Fruit 3. Auscold 4. AMJ 5. Musico 6. Sunraysia 7. SunFresh 7. Woolworths",
    "Priority" : "High",
    "start_date_time" : "2023-09-11",
    "end_date_time" : "2023-09-11",
    "Task_Recurrence" : "Daily",
    "Assign_to_User" : "Zoe",
    "Assign_to_Department" : "",
    "Escalated_to_User" : "",
    "Escalated_to_Department" : "",
    "Email_Notify" : false,
    "end_time" : "04:15",
    "start_time" : "03:15",
    "Task_Date" : "2023-09-11",
    "__v" : 0
},
{

    "is_task_done" : false,
    "is_task_rollovered" : false,
    "Monday" : false,
    "Thuesday" : false,
    "Wednesday" : false,
    "Thudesday" : false,
    "Friday" : false,
    "Saturday" : false,
    "Sunday" : false,
    "ID" : "4349e3b7-99f2-4da9-97e0-75029fbd091f",
    "Short_description" : "Record Packout Temperatures",
    "Summary" : "Record Packout Temperatures  This is a quality requirement, the form is number #18 and is found just outside the quality office",
    "Priority" : "High",
    "start_date_time" : "2023-09-11",
    "end_date_time" : "2023-09-11",
    "Task_Recurrence" : "Daily",
    "Assign_to_User" : "Zoe",
    "Assign_to_Department" : "",
    "Escalated_to_User" : "",
    "Escalated_to_Department" : "Picking",
    "Email_Notify" : false,
    "end_time" : "04:15",
    "start_time" : "03:15",
    "Task_Date" : "2023-09-11",
    "__v" : 0
},
{

    "is_task_done" : false,
    "is_task_rollovered" : false,
    "Monday" : false,
    "Thuesday" : false,
    "Wednesday" : false,
    "Thudesday" : false,
    "Friday" : false,
    "Saturday" : false,
    "Sunday" : false,
    "ID" : "685d9fdc-88d1-402e-b5e1-2271258df87e",
    "Short_description" : "Print Transport Manifest Summary",
    "Summary" : "No Summary",
    "Priority" : "High",
    "start_date_time" : "2023-09-11",
    "end_date_time" : "2023-09-11",
    "Task_Recurrence" : "Daily",
    "Assign_to_User" : "Zoe",
    "Assign_to_Department" : "",
    "Escalated_to_User" : "",
    "Escalated_to_Department" : "Picking",
    "Email_Notify" : false,
    "end_time" : "04:15",
    "start_time" : "03:15",
    "Task_Date" : "2023-09-11",
    "__v" : 0
},
{
    "is_task_done" : false,
    "is_task_rollovered" : false,
    "Monday" : false,
    "Thuesday" : false,
    "Wednesday" : false,
    "Thudesday" : false,
    "Friday" : false,
    "Saturday" : false,
    "Sunday" : false,
    "ID" : "53cb8dfe-eb47-49d5-abc1-3f71ab674eca",
    "Short_description" : "Start up for fridge Area",
    "Summary" : "Start up for fridge Area  This is used as feebcak to the pick pack dept about the state of the fridge at the end of their shift. ",
    "Priority" : "High",
    "start_date_time" : "2023-09-12",
    "end_date_time" : "2023-09-12",
    "Task_Recurrence" : "Daily",
    "Assign_to_User" : "",
    "Assign_to_Department" : "Picking",
    "Escalated_to_User" : "Zoe",
    "Escalated_to_Department" : "",
    "Email_Notify" : false,
    "end_time" : "05:29",
    "start_time" : "03:29",
    "Task_Date" : "2023-09-12",
    "__v" : 0
}


















{
    
    "Approve" : false,
    "ID" : "333187bd-608c-4ac4-af58-13436f2c314a",
    "Task_ID" : "4cd82f35-140d-4624-a330-192ec70f4d8b",
    "Type" : "Yes/NO",
    "MinValue" : "",
    "MaxValue" : "",
    "ExptectedValue" : "",
    "Questions" : "I have turned the alarm off ?",
    "User" : "Zoe",
    "Department" : "",
    "Date" : "2023-09-12",
    "EsUser" : "",
    "EsDepartment" : "Picking",
    "ApproveBy" : "Zoe",
    "__v" : 0
},
{
    
    "Approve" : false,
    "ID" : "f927efb3-0390-4352-ba79-eadace3968f0",
    "Task_ID" : "4cd82f35-140d-4624-a330-192ec70f4d8b",
    "Type" : "Yes/NO",
    "MinValue" : "",
    "MaxValue" : "",
    "ExptectedValue" : "",
    "Questions" : "I have unlocked coolroom B & C ?",
    "Date" : "2023-09-11",
    "__v" : 0
},
{
   
    "Approve" : false,
    "ID" : "c6edab54-dec2-4c14-9d77-da1978ef53ea",
    "Task_ID" : "4cd82f35-140d-4624-a330-192ec70f4d8b",
    "Type" : "Yes/NO",
    "MinValue" : "",
    "MaxValue" : "",
    "ExptectedValue" : "",
    "Questions" : "I have turned the lights on in the coolrooms ?",
    "Date" : "2023-09-11",
    "__v" : 0
},
{
  
    "Approve" : false,
    "ID" : "4fa92b92-eb49-43e4-9d48-0ccebb2abc36",
    "Task_ID" : "4cd82f35-140d-4624-a330-192ec70f4d8b",
    "Type" : "Yes/NO",
    "MinValue" : "",
    "MaxValue" : "",
    "ExptectedValue" : "",
    "Questions" : "I have my Radio, Knife, Thermometer & Pen ?",
    "Date" : "2023-09-11",
    "__v" : 0
},
{
   
    "Approve" : false,
    "ID" : "b9e1985b-f735-4c62-a7e3-170f4c37d875",
    "Task_ID" : "4cd82f35-140d-4624-a330-192ec70f4d8b",
    "Type" : "Yes/NO",
    "MinValue" : "",
    "MaxValue" : "",
    "ExptectedValue" : "",
    "Questions" : "I have the Morning Loaders phone on me ?",
    "Date" : "2023-09-11",
    "__v" : 0
},
{

    "Approve" : false,
    "ID" : "7b4ed68b-9b71-4baf-aa5e-c619553012c8",
    "Task_ID" : "1e89e19d-77c4-42a0-9b2e-4c8020d39e3d",
    "Type" : "Value",
    "MinValue" : "1",
    "MaxValue" : "100",
    "ExptectedValue" : "",
    "Questions" : "Who ordered overnight?",
    "User" : "Zoe",
    "Department" : "",
    "Date" : "2023-09-11",
    "EsUser" : "",
    "EsDepartment" : "Picking",
    "ApproveBy" : "Zoe",
    "__v" : 0
},
{

    "Approve" : false,
    "ID" : "9e95e9a4-736b-47d6-9b87-a6de4410b962",
    "Task_ID" : "c0903903-100d-4b59-b794-af763a6339f8",
    "Type" : "Attachement",
    "MinValue" : "",
    "MaxValue" : "",
    "ExptectedValue" : "",
    "Questions" : "Take a picture of the displays turned ON.",
    "User" : "",
    "Department" : "",
    "Date" : "2023-09-11",
    "EsUser" : "",
    "EsDepartment" : "",
    "ApproveBy" : "Zoe",
    "__v" : 0
},
{

    "Approve" : false,
    "ID" : "da422af4-959d-43df-8cee-890ce0f28092",
    "Task_ID" : "0d46fb13-c59e-4c70-9e31-781920d1ae61",
    "Type" : "Attachement",
    "MinValue" : "",
    "MaxValue" : "",
    "ExptectedValue" : "",
    "Questions" : "Take a picture of the displays turned ON.",
    "User" : "Zoe",
    "Department" : "",
    "Date" : "2023-09-11",
    "EsUser" : "",
    "EsDepartment" : "Picking",
    "ApproveBy" : "Zoe",
    "__v" : 0
},
{
    
    "Approve" : false,
    "ID" : "9b61e3ec-c666-48e7-840e-18161da68172",
    "Task_ID" : "0d46fb13-c59e-4c70-9e31-781920d1ae61",
    "Type" : "Attachement",
    "MinValue" : "",
    "MaxValue" : "",
    "ExptectedValue" : "",
    "Questions" : "Take a picture of the *HOT* fresh air fans turned OFF.",
    "Date" : "2023-09-11",
    "__v" : 0
},
{
    
    "Approve" : false,
    "ID" : "67f2de23-18c9-4e44-852e-4bfa084be94c",
    "Task_ID" : "535201bd-690e-4337-b379-e116add4c9ad",
    "Type" : "Attachement",
    "MinValue" : "",
    "MaxValue" : "",
    "ExptectedValue" : "",
    "Questions" : "Take a picture of the screen showing orders to be printed",
    "User" : "Zoe",
    "Department" : "",
    "Date" : "2023-09-11",
    "EsUser" : "",
    "EsDepartment" : "Picking",
    "ApproveBy" : "Zoe",
    "__v" : 0
},
{
   
    "Approve" : false,
    "ID" : "409c69e9-5b93-47df-97e0-6845faa8a274",
    "Task_ID" : "51e2e1e7-c690-4b1b-957e-d41b400a75f2",
    "Type" : "Attachement",
    "MinValue" : "",
    "MaxValue" : "",
    "ExptectedValue" : "",
    "Questions" : "Take a picture of the report and labels on the bench just outside the ladies toilets",
    "User" : "Zoe",
    "Department" : "",
    "Date" : "2023-09-11",
    "EsUser" : "",
    "EsDepartment" : "Picking",
    "ApproveBy" : "Zoe",
    "__v" : 0
},
{
    
    "Approve" : false,
    "ID" : "5901bf02-e61e-43a0-964d-322e869dccff",
    "Task_ID" : "b3742e93-0183-4c44-8f8e-82dc420fd81b",
    "Type" : "Attachement",
    "MinValue" : "",
    "MaxValue" : "",
    "ExptectedValue" : "",
    "Questions" : "Take a picture of the printed report",
    "User" : "Zoe",
    "Department" : "",
    "Date" : "2023-09-11",
    "EsUser" : "",
    "EsDepartment" : "Picking",
    "ApproveBy" : "Zoe",
    "__v" : 0
},
{
   
    "Approve" : false,
    "ID" : "1fec4d85-809f-4b0f-afe5-ee20ec2318b0",
    "Task_ID" : "6c5a1282-e24c-46c9-a686-954f9ecfa492",
    "Type" : "Attachement",
    "MinValue" : "",
    "MaxValue" : "",
    "ExptectedValue" : "",
    "Questions" : "I have considered what's going out today",
    "User" : "Zoe",
    "Department" : "",
    "Date" : "2023-09-11",
    "EsUser" : "",
    "EsDepartment" : "Picking",
    "ApproveBy" : "Zoe",
    "__v" : 0
},
{
    
    "Approve" : false,
    "ID" : "42cea14b-c047-4cbe-b4c0-9a77ba34c6a6",
    "Task_ID" : "a1fdb578-2494-4860-8280-7dafc6e868cd",
    "Type" : "Yes/NO",
    "MinValue" : "",
    "MaxValue" : "",
    "ExptectedValue" : "",
    "Questions" : "I have loaded Central Fruit & Veg",
    "User" : "Zoe",
    "Department" : "",
    "Date" : "2023-09-11",
    "EsUser" : "",
    "EsDepartment" : "",
    "ApproveBy" : "Zoe",
    "__v" : 0
},
{

    "Approve" : false,
    "ID" : "1699e196-b33f-40a0-8e56-f0559f62ea22",
    "Task_ID" : "a1fdb578-2494-4860-8280-7dafc6e868cd",
    "Type" : "Yes/NO",
    "MinValue" : "",
    "MaxValue" : "",
    "ExptectedValue" : "",
    "Questions" : "I have loaded Sunraysia Transport pallet",
    "Date" : "2023-09-11",
    "__v" : 0
},
{
   
    "Approve" : false,
    "ID" : "94f9acbd-3d8d-45eb-95f3-24b782208350",
    "Task_ID" : "a1fdb578-2494-4860-8280-7dafc6e868cd",
    "Type" : "Yes/NO",
    "MinValue" : "",
    "MaxValue" : "",
    "ExptectedValue" : "",
    "Questions" : "I have loaded HS Fresh Bins",
    "Date" : "2023-09-11",
    "__v" : 0
},
{
 
    "Approve" : false,
    "ID" : "b349aefd-49a3-4a48-8d2d-3a3e1684b96a",
    "Task_ID" : "a1fdb578-2494-4860-8280-7dafc6e868cd",
    "Type" : "Yes/NO",
    "MinValue" : "",
    "MaxValue" : "",
    "ExptectedValue" : "",
    "Questions" : "I have checked WV pallets reject returns in CR C",
    "Date" : "2023-09-11",
    "__v" : 0
},
{
    
    "Approve" : false,
    "ID" : "1465a6c5-c47b-471b-9ba3-adc39d323621",
    "Task_ID" : "a1fdb578-2494-4860-8280-7dafc6e868cd",
    "Type" : "Yes/NO",
    "MinValue" : "",
    "MaxValue" : "",
    "ExptectedValue" : "",
    "Questions" : "I have considered whether i need to load Auscold HJ's NT?",
    "Date" : "2023-09-11",
    "__v" : 0
},
{
    
    "Approve" : false,
    "ID" : "ec0da0e1-8f64-49bf-b059-18ff1989a459",
    "Task_ID" : "4349e3b7-99f2-4da9-97e0-75029fbd091f",
    "Type" : "Attachement",
    "MinValue" : "",
    "MaxValue" : "",
    "ExptectedValue" : "",
    "Questions" : "Take a picture of front page after filled out",
    "User" : "Zoe",
    "Department" : "",
    "Date" : "2023-09-11",
    "EsUser" : "",
    "EsDepartment" : "Picking",
    "ApproveBy" : "Zoe",
    "__v" : 0
},
{
    
    "Approve" : false,
    "ID" : "c6128a40-d2cb-4d54-9605-4334c5fe65d5",
    "Task_ID" : "4349e3b7-99f2-4da9-97e0-75029fbd091f",
    "Type" : "Attachement",
    "MinValue" : "",
    "MaxValue" : "",
    "ExptectedValue" : "",
    "Questions" : "Take a picture of back page after filled out",
    "Date" : "2023-09-11",
    "__v" : 0
}